---
title: "preparing figures"
author: "Jonathan Rosenblatt"
date: "7/26/2016"
output: html_document
---

```{r preliminaries}
setwd('~/workspace/Gilron/')
source('Gilron Effect of Cross Validatino.R')

```

```{r}
load('2016-07-16 14:51:27')
```


```{r}
pvals.1.9 %<>%  tbl_df
pvals.melt <- melt(pvals.1.9, id.vars=c("effect"), variable.name='statistic') %>% tbl_df

pvals.melt %<>% mutate(reject= as.numeric(value <= 0.05)) 

plot.2 <- pvals.melt %>% 
  filter(
    statistic != 'pval.svm.refold.fixTest' ,
    statistic != 'pval.svm.fixTest' ,
    statistic != 'pval.lda.refold.fixTest',
    statistic != 'pval.lda.fixTest',
    statistic != 'pval.lda.fixTest') %>%
  # ggplot(aes(y=reject, x=effect, group=statistic, color=statistic, shape=statistic)) +
  ggplot(aes(y=reject, x=effect, group=statistic, color=statistic)) +
  theme_bw(base_size = 20)+
  # ggtitle("Fixed signal, Gaussian Noise")+
  xlab('Effect')+
  ylab('Power')+
  stat_summary(fun.y='mean', geom="line") +
  # stat_summary(fun.data = mean_cl_normal, geom = "errorbar")
  stat_summary(fun.y='mean', geom="point") +
  geom_hline(yintercept=0.05, lty=2)

plot.2

```



```{r}
pvals.1.9.1 <- filter(pvals.1.9, effect==0)
  
powers <- cbind(round(apply(pvals.1.9.1, 2, function(x) mean(x<=0.05, na.rm=TRUE)),3))
the.title <- sprintf('cost=%g, permutations=%d, replications=%d, n=%d, p=%d, n.folds=%d, shrinkage=%s, errror bar=%s, balance=%s', cost, n.permutations, n.replications, n, p, n.folds, shrinkage, err.bar, balance)

powers

.limits <- 0.05 + c(-err.bar,0,err.bar)
# dotchart(powers); abline(v=.limits, lty=c(3,2,3))
dotchart(powers, xlim=c(0,0.1)); abline(v=.limits, lty=c(3,2,3));title(the.title)
# dotchart(powers, xlim=c(0.04,0.1)); abline(v=.limits, lty=c(3,2,3)) #;title(the.title)

# pdf(file = 'dotplot.pdf')
# dotchart(powers, xlim=c(0.04,0.1)); abline(v=.limits, lty=c(3,2,3));title(the.title)
# dev.off()
# pbPost("file", filetype = 'application/pdf', url='~/workspace/Gilron/dotplot.pdf')
```


```{r}
for(i in 2:ncol(pvals.1.9.1)){
  plot(table(pvals.1.9.1[,i]))
  title(paste(names(pvals.1.9.1[i])))
}
```
```

