---
title: "Logistic Regression (main and interactions, original space)"
author: "Jonathan Rosenblatt"
date: "23/1/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
n.permutations <- 3e2
n.replications <-  1e2
```


```{r preliminaries}
file.name <- "file41"
setwd('~/workspace/permuting_accuracy/Round4/')

p <- 23
n <- 4e1 # total sample size-> n/2 in each group.
n.folds <- 4

source('Gilron Effect of Cross Validatino.R')

Sigma <- diag(p)
Sigma.inv <- solve(Sigma)
p.quadratic <- choose(p,2)
p.total <- p+p.quadratic
beta0 <- c(rep(1,p),rep(0.01,p.quadratic))
effects <- c(0,0.5,2)
```


## Fixed folds. Cross-Validated. All in one.
```{r}
RhpcBLASctl::blas_set_num_threads(1)
registerDoMC(cores=100)
```

```{r independent noise variable folds}
pvals.1.9 <- foreach(j=1:n.replications, .combine=rbind) %dopar%{
  foreach(effect=effects, .combine=rbind)  %do% {
    
    ## Gaussian noise
    noise <- matrix(rnorm(n*p), ncol=p, nrow=n)
    noise.augment <- model.matrix(~.^2-1, as.data.frame(noise))
    
    ## Logistic regression
    # effect <- effects[[3]]
    beta <- beta0*effect
    link <- noise.augment%*%beta
    probs <- plogis(link)
    # plot(probs, type='h')
    
    # Force balanced groups:
    labels <- c(TRUE,FALSE)[rbinom(n,1, probs)+1] # group assignemt labels
    
    ## Compute observed statistic
    x1 <- noise[labels,]
    x2 <- noise[!labels,]
    
    ## Asign observations to folds. Use the simple label structure to balance folds.
    fold.ids <- balanced_folding(labels, n.folds, balance = TRUE)
    # capture.output(table(fold.ids, labels), file=balance.log, append = TRUE)
    
    # Observables 
    ts <-statistics(x1 = x1, 
                    x2 = x2, 
                    Sigma.inv = Sigma.inv, 
                    noise = noise, 
                    labels = labels, 
                    fold.ids = fold.ids)
    
    # Prepare to permute
    old.labels <- labels
    old.folds.ids <- fold.ids
    
    # Initialize permuted statistics
    permuted <- matrix(NA, ncol=length(ts), nrow=n.permutations)
    
    for(i in 1:n.permutations){
      # i <- 1
      
      labels <- sample(labels) # label switching
      fold.ids <- balanced_folding(labels, n.folds, TRUE) # refold
      x1 <- noise[labels,]
      x2 <- noise[!labels,]
      
      permuted[i,] <- statistics(x1 = x1, 
                                 x2 = x2,
                                 Sigma.inv =Sigma.inv, 
                                 noise = noise,
                                 labels = labels,
                                 fold.ids = fold.ids)
    } # End permutation
    
    # Compute p-vals for each statistic
    pvals <- rep(NA, length(ts))
    for(i in seq_along(ts)){
      # i <- 1
      pvals[i] <- mean(permuted[,i]>=ts[i], na.rm=TRUE)
    }
    names(pvals) <- names(ts)
    
    c(effect=effect, pvals, replication=j) 
  }
} 

pbPost(type = "note", body = "File2", title = the.message)
save.image(file=paste(file.name,".RData", sep=''))
```

## Analysis
```{r}
# load('file41.RData')
source('prepare_graphics.R')
plot(plot.3)
```

```{r}
pdf(file = paste('Output/',file.name,'.pdf', sep=''))
plot(plot.3)
dev.off()
```

